// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBmG5y1CCLQwy_81Szyl-azD9cP7C4yJ0',
    appId: '1:811505798364:web:9eb88d0c72e7774fbd7819',
    messagingSenderId: '811505798364',
    projectId: 'edpal-60c29',
    authDomain: 'edpal-60c29.firebaseapp.com',
    databaseURL: 'https://edpal-60c29-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edpal-60c29.appspot.com',
    measurementId: 'G-KQ9V9KXE2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQTyiO_yMy-uw5VtNjI5x0x4jmfGuOAAU',
    appId: '1:811505798364:android:83fd42929535d311bd7819',
    messagingSenderId: '811505798364',
    projectId: 'edpal-60c29',
    databaseURL: 'https://edpal-60c29-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edpal-60c29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnMoEoPpiz2CDfFiXOjJbMoGR07TfUC0U',
    appId: '1:811505798364:ios:c18212ffca05c366bd7819',
    messagingSenderId: '811505798364',
    projectId: 'edpal-60c29',
    databaseURL: 'https://edpal-60c29-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edpal-60c29.appspot.com',
    iosBundleId: 'com.edpal.edpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnMoEoPpiz2CDfFiXOjJbMoGR07TfUC0U',
    appId: '1:811505798364:ios:c18212ffca05c366bd7819',
    messagingSenderId: '811505798364',
    projectId: 'edpal-60c29',
    databaseURL: 'https://edpal-60c29-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edpal-60c29.appspot.com',
    iosBundleId: 'com.edpal.edpal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBmG5y1CCLQwy_81Szyl-azD9cP7C4yJ0',
    appId: '1:811505798364:web:dc50b64321db26a6bd7819',
    messagingSenderId: '811505798364',
    projectId: 'edpal-60c29',
    authDomain: 'edpal-60c29.firebaseapp.com',
    databaseURL: 'https://edpal-60c29-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edpal-60c29.appspot.com',
    measurementId: 'G-7VKWC2STV7',
  );

}